env: flex
runtime: nodejs
service: memory-leak-test
endpoints_api_service:
  name: memory-leak-test.endpoints.PROJECT_ID.cloud.goog
automatic_scaling:
  min_num_instances: 1
resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10
env_variables:
  NODE_ENV: production
  API_ENV: production
  IS_DEPLOYED: true
liveness_check:
  path: /memory_leak_test/liveness_check
readiness_check:
  path: /memory_leak_test/readiness_check
